// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPJmWhIe17JNd-RQ7fGEoAIOy5O2Wqnrk',
    appId: '1:242900292848:web:02639f7fccf1194f68de35',
    messagingSenderId: '242900292848',
    projectId: 'firepractice-b578e',
    authDomain: 'firepractice-b578e.firebaseapp.com',
    storageBucket: 'firepractice-b578e.firebasestorage.app',
    measurementId: 'G-5NY5R27XD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYXZHQAA11vyg8Z5Rbbl0nm0pDPuPSKXs',
    appId: '1:242900292848:android:d10937661cefb93268de35',
    messagingSenderId: '242900292848',
    projectId: 'firepractice-b578e',
    storageBucket: 'firepractice-b578e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1XeeuTRTmBad-zkmHFiQP-t6ThUGWZbg',
    appId: '1:242900292848:ios:924ce57e3cae27e568de35',
    messagingSenderId: '242900292848',
    projectId: 'firepractice-b578e',
    storageBucket: 'firepractice-b578e.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1XeeuTRTmBad-zkmHFiQP-t6ThUGWZbg',
    appId: '1:242900292848:ios:924ce57e3cae27e568de35',
    messagingSenderId: '242900292848',
    projectId: 'firepractice-b578e',
    storageBucket: 'firepractice-b578e.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPJmWhIe17JNd-RQ7fGEoAIOy5O2Wqnrk',
    appId: '1:242900292848:web:246de9c7b03be78868de35',
    messagingSenderId: '242900292848',
    projectId: 'firepractice-b578e',
    authDomain: 'firepractice-b578e.firebaseapp.com',
    storageBucket: 'firepractice-b578e.firebasestorage.app',
    measurementId: 'G-VS846Y93MV',
  );
}
